### ISSUE TITLE
Trouble building on Digital Ocean

### ISSUE THREAD

**Issue by sgehrman** [lenondupe/stellar-ledger-api#8]
Going to sleep, but stuck on this.  If you have ideas, let me know

steve@stellar-node:~/github/stellarkit.io$ nodejs -v
v9.4.0
steve@stellar-node:~/github/stellarkit.io$ npm -v
5.6.0

yarn install gives me this:

http GET https://github.com/node-hid/node-hid/releases/download/0.5.4/HID-v0.5.4-node-v59-linux-x64.tar.gz
node-pre-gyp http 404 https://github.com/node-hid/node-hid/releases/download/0.5.4/HID-v0.5.4-node-v59-linux-x64.tar.gz

Found this:   https://github.com/node-hid/node-hid/issues/213

also...

node-pre-gyp ERR! Tried to download(404): https://github.com/node-hid/node-hid/releases/download/0.5.4/HID-v0.5.4-node-v59-linux-x64.tar.gz
node-pre-gyp ERR! Pre-built binaries not found for node-hid@0.5.4 and node@9.4.0 (node-v59 ABI) (falling back to source compile with node-gyp)
node-pre-gyp http 404 status code downloading tarball https://github.com/node-hid/node-hid/releases/download/0.5.4/HID-v0.5.4-node-v59-linux-x64.tar.gz
gyp info it worked if it ends with ok
gyp info using node-gyp@3.6.2
gyp info using node@9.4.0 | linux | x64
gyp info ok
gyp info it worked if it ends with ok
gyp info using node-gyp@3.6.2
gyp info using node@9.4.0 | linux | x64
gyp info spawn /usr/bin/python2
gyp info spawn args [ '/home/steve/github/stellarkit.io/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/home/steve/github/stellarkit.io/node_modules/node-hid/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/home/steve/github/stellarkit.io/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/home/steve/.node-gyp/9.4.0/include/node/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/home/steve/.node-gyp/9.4.0',
gyp info spawn args   '-Dnode_gyp_dir=/home/steve/github/stellarkit.io/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=/home/steve/.node-gyp/9.4.0/<(target_arch)/node.lib',
gyp info spawn args   '-Dmodule_root_dir=/home/steve/github/stellarkit.io/node_modules/node-hid',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.' ]
gyp info ok
gyp info it worked if it ends with ok
gyp info using node-gyp@3.6.2
gyp info using node@9.4.0 | linux | x64
gyp info spawn make
gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
make: Entering directory '/home/steve/github/stellarkit.io/node_modules/node-hid/build'
  CC(target) Release/obj.target/hidapi/hidapi/libusb/hid.o
../hidapi/libusb/hid.c:47:20: fatal error: libusb.h: No such file or directory
compilation terminated.
hidapi.target.mk:97: recipe for target 'Release/obj.target/hidapi/hidapi/libusb/hid.o' failed
make: Leaving directory '/home/steve/github/stellarkit.io/node_modules/node-hid/build'
make: *** [Release/obj.target/hidapi/hidapi/libusb/hid.o] Error 1
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/home/steve/github/stellarkit.io/node_modules/node-gyp/lib/build.js:258:23)
gyp ERR! stack     at ChildProcess.emit (events.js:160:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:12)
gyp ERR! System Linux 4.4.0-109-generic
gyp ERR! command "/usr/bin/node" "/home/steve/github/stellarkit.io/node_modules/node-gyp/bin/node-gyp.js" "build" "--fallback-to-build" "--module=/home/steve/github/stellarkit.io/node_modules/node-hid/build/Release/HID.node" "--module_name=HID" "--module_path=/home/steve/github/stellarkit.io/node_modules/node-hid/build/Release"
gyp ERR! cwd /home/steve/github/stellarkit.io/node_modules/node-hid
gyp ERR! node -v v9.4.0
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
node-pre-gyp ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute '/usr/bin/node /home/steve/github/stellarkit.io/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/home/steve/github/stellarkit.io/node_modules/node-hid/build/Release/HID.node --module_name=HID --module_path=/home/steve/github/stellarkit.io/node_modules/node-hid/build/Release' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/home/steve/github/stellarkit.io/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:160:13)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:943:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:220:5)
node-pre-gyp ERR! System Linux 4.4.0-109-generic
node-pre-gyp ERR! command "/usr/bin/node" "/home/steve/github/stellarkit.io/node_modules/node-hid/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /home/steve/github/stellarkit.io/node_modules/node-hid
node-pre-gyp ERR! node -v v9.4.0
node-pre-gyp ERR! node-pre-gyp -v v0.6.31

**Comment by sgehrman** [comment]
I had to install

sudo apt install libusb-1.0-0-dev
